# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='gender',
            field=models.CharField(blank=True, choices=[('s', ' student'), ('t', 'teacher')], max_length=128, null=True),
        ),
    ]
