# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20170105_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(blank=True, choices=[('s', ' student'), ('t', 'teacher')], default='s', max_length=128, null=True),
        ),
    ]
