# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20170105_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(choices=[('s', ' student'), ('t', 'teacher')], default='s', max_length=128),
        ),
    ]
