# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='document'),
            preserve_default=False,
        ),
    ]
