# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_auto_20170106_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='image',
        ),
        migrations.AddField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='documents'),
            preserve_default=False,
        ),
    ]
